# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - innovation-front

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://innovationplusacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_e52c4fa5c16a4c379b0b72c6432c7a4a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ba1d0aa7faf34224a93628bdf3e2feef }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: innovationplusacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e52c4fa5c16a4c379b0b72c6432c7a4a }}/local-dev_innovation-front:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'innovation-front'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6c43232c67c84750a6d8e03452d08296 }}
        images: 'innovationplusacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_e52c4fa5c16a4c379b0b72c6432c7a4a }}/local-dev_innovation-front:${{ github.sha }}'